-- Core schema for Pushbike Race Management System
create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

-- Enums
do $$
begin
  if not exists (select 1 from pg_type where typname = 'event_status') then
    create type event_status as enum ('UPCOMING','LIVE','FINISHED');
  end if;
  if not exists (select 1 from pg_type where typname = 'gender_type') then
    create type gender_type as enum ('BOY','GIRL','MIX');
  end if;
  if not exists (select 1 from pg_type where typname = 'moto_status') then
    create type moto_status as enum ('UPCOMING','LIVE','FINISHED','PROVISIONAL','PROTEST_REVIEW','LOCKED');
  end if;
  if not exists (select 1 from pg_type where typname = 'result_status') then
    create type result_status as enum ('FINISH','DNF','DNS');
  end if;
  if not exists (select 1 from pg_type where typname = 'registration_status') then
    create type registration_status as enum ('PENDING','APPROVED','REJECTED');
  end if;
  if not exists (select 1 from pg_type where typname = 'registration_item_status') then
    create type registration_item_status as enum ('PENDING','APPROVED','REJECTED');
  end if;
  if not exists (select 1 from pg_type where typname = 'registration_document_type') then
    create type registration_document_type as enum ('KK','AKTE');
  end if;
  if not exists (select 1 from pg_type where typname = 'registration_payment_status') then
    create type registration_payment_status as enum ('PENDING','APPROVED','REJECTED');
  end if;
  if not exists (select 1 from pg_type where typname = 'registration_payment_method') then
    create type registration_payment_method as enum ('MANUAL_TRANSFER');
  end if;
end$$;

-- Optional module enums
do $$
begin
  if not exists (select 1 from pg_type where typname = 'penalty_stage') then
    create type penalty_stage as enum ('MOTO','QUARTER','SEMI','FINAL','ALL');
  end if;
  if not exists (select 1 from pg_type where typname = 'participation_status') then
    create type participation_status as enum ('ACTIVE','DNS','DNF','ABSENT');
  end if;
  if not exists (select 1 from pg_type where typname = 'rank_type') then
    create type rank_type as enum ('COMPETITIVE','ADMINISTRATIVE');
  end if;
  if not exists (select 1 from pg_type where typname = 'award_type') then
    create type award_type as enum (
      'PARTICIPATION',
      'BEGINNER','AMATEUR','ACADEMY','ROOKIE','PRO','NOVICE','ELITE','INTERMEDIATE','ADVANCED'
    );
  end if;
  if not exists (select 1 from pg_type where typname = 'approval_mode') then
    create type approval_mode as enum ('AUTO','DIRECTOR');
  end if;
  if not exists (select 1 from pg_type where typname = 'approval_status') then
    create type approval_status as enum ('PENDING','APPROVED','REJECTED');
  end if;
  if not exists (select 1 from pg_type where typname = 'audit_action') then
    create type audit_action as enum ('STATUS_APPROVAL','PENALTY_APPROVAL','RESULT_OVERRIDE','RESULT_UNLOCK');
  end if;
  if not exists (select 1 from pg_type where typname = 'race_stage') then
    create type race_stage as enum ('QUALIFICATION','QUARTER_FINAL','SEMI_FINAL','FINAL');
  end if;
  if not exists (select 1 from pg_type where typname = 'final_class') then
    create type final_class as enum (
      'BEGINNER','AMATEUR','ACADEMY','ROOKIE','PRO','NOVICE','ELITE','INTERMEDIATE','ADVANCED'
    );
  end if;
  if not exists (select 1 from pg_type where typname = 'protest_decision') then
    create type protest_decision as enum ('PENDING','ACCEPTED','REJECTED');
  end if;
end$$;

-- Shared helper to keep updated_at consistent
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- EVENTS
create table if not exists events (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  location text,
  event_date date not null,
  status event_status not null default 'UPCOMING',
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_events_status on events(status);
create index if not exists idx_events_date on events(event_date);

drop trigger if exists trg_events_updated_at on events;
create trigger trg_events_updated_at
before update on events
for each row execute function set_updated_at();

-- CATEGORIES (auto-generated by year + gender)
create table if not exists categories (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  year int not null,
  year_min int not null default 2017,
  year_max int not null default 2017,
  capacity int,
  gender gender_type not null,
  label text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  constraint ck_categories_capacity check (capacity is null or capacity >= 0)
);

create index if not exists idx_categories_event on categories(event_id);
create index if not exists idx_categories_year_gender on categories(event_id, year, gender);
create unique index if not exists uq_categories_event_year_gender on categories(event_id, year, gender);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'ck_categories_year_range') then
    alter table categories
      add constraint ck_categories_year_range check (year_min <= year_max);
  end if;
end$$;

-- RIDERS
create table if not exists riders (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  name text not null,
  rider_nickname text,
  jersey_size text,
  date_of_birth date not null,
  birth_year int generated always as (extract(year from date_of_birth)::int) stored,
  primary_category_id uuid references categories(id) on delete set null,
  gender gender_type not null,
  plate_number text not null,
  plate_suffix char(1),
  no_plate_display text generated always as (
    plate_number || coalesce(plate_suffix::text, '')
  ) stored,
  club text,
  photo_url text,
  photo_thumbnail_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_rider_gender check (gender in ('BOY','GIRL')),
  constraint ck_plate_number check (plate_number ~ '^[0-9]+$'),
  constraint ck_plate_suffix check (plate_suffix is null or plate_suffix ~ '^[A-Z]$'),
  constraint ck_rider_jersey_size check (jersey_size is null or jersey_size in ('XS','S','M','L','XL','2XL','3XL')),
  constraint ck_birth_year check (
    birth_year >= 2016
    and birth_year <= 2025
  )
);

create unique index if not exists uq_riders_plate_per_event on riders(event_id, plate_number, plate_suffix);
create index if not exists idx_riders_event on riders(event_id);
create index if not exists idx_riders_no_plate on riders(event_id, plate_number, plate_suffix);
create index if not exists idx_riders_primary_category on riders(primary_category_id);

drop trigger if exists trg_riders_updated_at on riders;
create trigger trg_riders_updated_at
before update on riders
for each row execute function set_updated_at();

-- MOTOS
create table if not exists motos (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  category_id uuid not null references categories(id) on delete cascade,
  moto_name text not null,
  moto_order int not null,
  status moto_status not null default 'UPCOMING',
  is_published boolean not null default false,
  published_at timestamptz,
  provisional_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_motos_event on motos(event_id);
create index if not exists idx_motos_category on motos(category_id);

-- MOTO RIDERS
create table if not exists moto_riders (
  id uuid primary key default uuid_generate_v4(),
  moto_id uuid not null references motos(id) on delete cascade,
  rider_id uuid not null references riders(id) on delete cascade,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_moto_rider on moto_riders(moto_id, rider_id);

-- RESULTS
create table if not exists results (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  moto_id uuid not null references motos(id) on delete cascade,
  rider_id uuid not null references riders(id) on delete cascade,
  finish_order int,
  result_status result_status not null default 'FINISH',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_results_moto_rider on results(moto_id, rider_id);
create index if not exists idx_results_moto on results(moto_id);
create index if not exists idx_results_event on results(event_id);
create unique index if not exists uq_results_moto_finish_order on results(moto_id, finish_order) where finish_order is not null;

drop trigger if exists trg_results_updated_at on results;
create trigger trg_results_updated_at
before update on results
for each row execute function set_updated_at();

-- RACE SCHEDULE
create table if not exists race_schedules (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  moto_id uuid not null references motos(id) on delete cascade,
  schedule_time timestamptz,
  end_time timestamptz,
  track_number int,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_race_schedules_event_moto on race_schedules(event_id, moto_id);
create index if not exists idx_race_schedules_event_time on race_schedules(event_id, schedule_time);

drop trigger if exists trg_race_schedules_updated_at on race_schedules;
create trigger trg_race_schedules_updated_at
before update on race_schedules
for each row execute function set_updated_at();

-- EVENT SETTINGS
create table if not exists event_settings (
  event_id uuid primary key references events(id) on delete cascade,
  event_logo_url text,
  sponsor_logo_urls text[] not null default '{}',
  base_price int not null default 250000,
  extra_price int not null default 150000,
  registration_open boolean not null default true,
  require_jersey_size boolean not null default false,
  scoring_rules jsonb not null default '{}'::jsonb,
  display_theme jsonb not null default '{}'::jsonb,
  race_format_settings jsonb not null default '{}'::jsonb,
  business_settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_event_settings_updated_at on event_settings;
create trigger trg_event_settings_updated_at
before update on event_settings
for each row execute function set_updated_at();

-- REGISTRATIONS
create table if not exists registrations (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  community_name text,
  contact_name text not null,
  contact_phone text not null,
  contact_email text,
  total_amount int not null default 0,
  status registration_status not null default 'PENDING',
  notes text,
  upload_token text,
  upload_token_created_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_registrations_total_amount check (total_amount >= 0)
);

create index if not exists idx_registrations_event on registrations(event_id);
create index if not exists idx_registrations_status on registrations(event_id, status);
create unique index if not exists registrations_upload_token_unique on registrations(upload_token) where upload_token is not null;

drop trigger if exists trg_registrations_updated_at on registrations;
create trigger trg_registrations_updated_at
before update on registrations
for each row execute function set_updated_at();

create table if not exists registration_items (
  id uuid primary key default uuid_generate_v4(),
  registration_id uuid not null references registrations(id) on delete cascade,
  rider_name text not null,
  rider_nickname text,
  jersey_size text,
  date_of_birth date not null,
  gender gender_type not null,
  club text,
  primary_category_id uuid references categories(id) on delete set null,
  extra_category_id uuid references categories(id) on delete set null,
  requested_plate_number text,
  requested_plate_suffix char(1),
  photo_url text,
  price int not null default 0,
  status registration_item_status not null default 'PENDING',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_registration_items_gender check (gender in ('BOY','GIRL')),
  constraint ck_registration_items_price check (price >= 0),
  constraint ck_registration_items_requested_plate_number check (
    requested_plate_number is null or requested_plate_number ~ '^[0-9]+$'
  ),
  constraint ck_registration_items_requested_plate_suffix check (
    requested_plate_suffix is null or requested_plate_suffix ~ '^[A-Z]$'
  ),
  constraint ck_registration_items_jersey_size check (
    jersey_size is null or jersey_size in ('XS','S','M','L','XL','2XL','3XL')
  )
);

create index if not exists idx_registration_items_registration on registration_items(registration_id);
create index if not exists idx_registration_items_status on registration_items(registration_id, status);
create index if not exists idx_registration_items_primary_category on registration_items(primary_category_id);
create index if not exists idx_registration_items_extra_category on registration_items(extra_category_id);

drop trigger if exists trg_registration_items_updated_at on registration_items;
create trigger trg_registration_items_updated_at
before update on registration_items
for each row execute function set_updated_at();

create table if not exists registration_documents (
  id uuid primary key default uuid_generate_v4(),
  registration_id uuid not null references registrations(id) on delete cascade,
  registration_item_id uuid references registration_items(id) on delete set null,
  document_type registration_document_type not null,
  file_url text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_registration_documents_registration on registration_documents(registration_id);
create index if not exists idx_registration_documents_item on registration_documents(registration_item_id);

create table if not exists registration_payments (
  id uuid primary key default uuid_generate_v4(),
  registration_id uuid not null references registrations(id) on delete cascade,
  amount int not null,
  bank_name text,
  account_name text,
  account_number text,
  proof_url text not null,
  status registration_payment_status not null default 'PENDING',
  payment_method registration_payment_method not null default 'MANUAL_TRANSFER',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_registration_payments_amount check (amount >= 0)
);

create index if not exists idx_registration_payments_registration on registration_payments(registration_id);
create index if not exists idx_registration_payments_status on registration_payments(status);

drop trigger if exists trg_registration_payments_updated_at on registration_payments;
create trigger trg_registration_payments_updated_at
before update on registration_payments
for each row execute function set_updated_at();

-- OPTIONAL MODULES

create table if not exists event_feature_flags (
  event_id uuid primary key references events(id) on delete cascade,
  penalty_enabled boolean not null default false,
  absent_enabled boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists rider_participation_status (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  rider_id uuid not null references riders(id) on delete cascade,
  participation_status participation_status not null default 'ACTIVE',
  registration_order int not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_rider_participation_event_rider
  on rider_participation_status(event_id, rider_id);

create table if not exists event_penalty_rules (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  code text not null,
  description text,
  penalty_point int not null,
  applies_to_stage penalty_stage not null default 'ALL',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_event_penalty_code
  on event_penalty_rules(event_id, code);
create index if not exists idx_event_penalty_event
  on event_penalty_rules(event_id);

create table if not exists rider_penalties (
  id uuid primary key default uuid_generate_v4(),
  rider_id uuid not null references riders(id) on delete cascade,
  event_id uuid not null references events(id) on delete cascade,
  stage penalty_stage not null default 'ALL',
  rule_code text not null,
  penalty_point int not null,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists idx_rider_penalties_event
  on rider_penalties(event_id);
create index if not exists idx_rider_penalties_rider
  on rider_penalties(rider_id);

create table if not exists event_absent_config (
  event_id uuid primary key references events(id) on delete cascade,
  absent_point int not null default 99,
  created_at timestamptz not null default now()
);

create table if not exists race_awards (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  rider_id uuid not null references riders(id) on delete cascade,
  category_id uuid references categories(id) on delete set null,
  stage penalty_stage not null default 'ALL',
  rank_type rank_type not null default 'COMPETITIVE',
  award_type award_type not null default 'PARTICIPATION',
  position int,
  created_at timestamptz not null default now()
);

create index if not exists idx_race_awards_event
  on race_awards(event_id);
create index if not exists idx_race_awards_rider
  on race_awards(rider_id);

create table if not exists event_approval_modes (
  event_id uuid primary key references events(id) on delete cascade,
  approval_mode approval_mode not null default 'AUTO',
  created_at timestamptz not null default now()
);

create table if not exists rider_status_updates (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  rider_id uuid not null references riders(id) on delete cascade,
  proposed_status participation_status not null,
  created_by text not null,
  approval_status approval_status not null default 'PENDING',
  approved_by text,
  approved_at timestamptz,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists idx_rider_status_updates_event
  on rider_status_updates(event_id);

create table if not exists rider_penalty_approvals (
  id uuid primary key default uuid_generate_v4(),
  penalty_id uuid not null references rider_penalties(id) on delete cascade,
  approval_status approval_status not null default 'PENDING',
  approved_by text,
  approved_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_rider_penalty_approvals_penalty
  on rider_penalty_approvals(penalty_id);

create table if not exists moto_locks (
  moto_id uuid primary key references motos(id) on delete cascade,
  event_id uuid not null references events(id) on delete cascade,
  is_locked boolean not null default true,
  locked_by text not null,
  locked_at timestamptz not null default now(),
  unlocked_by text,
  unlocked_at timestamptz,
  reason text
);

create table if not exists audit_log (
  id uuid primary key default uuid_generate_v4(),
  action_type audit_action not null,
  performed_by text not null,
  rider_id uuid references riders(id) on delete set null,
  moto_id uuid references motos(id) on delete set null,
  event_id uuid references events(id) on delete set null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists moto_gate_positions (
  id uuid primary key default uuid_generate_v4(),
  moto_id uuid not null references motos(id) on delete cascade,
  rider_id uuid not null references riders(id) on delete cascade,
  gate_position int not null,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_moto_gate_positions
  on moto_gate_positions(moto_id, rider_id);
create index if not exists idx_moto_gate_positions_moto
  on moto_gate_positions(moto_id);

create table if not exists rider_extra_categories (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  rider_id uuid not null references riders(id) on delete cascade,
  category_id uuid not null references categories(id) on delete cascade,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_rider_extra_category_rider
  on rider_extra_categories(rider_id);
create index if not exists idx_rider_extra_category_event
  on rider_extra_categories(event_id);
create index if not exists idx_rider_extra_category_category
  on rider_extra_categories(category_id);

create table if not exists event_safety_requirements (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references events(id) on delete cascade,
  label text not null,
  is_required boolean not null default true,
  sort_order integer not null default 0,
  penalty_code text,
  created_at timestamptz not null default now()
);

create index if not exists event_safety_requirements_event_id_idx
  on event_safety_requirements(event_id);
create unique index if not exists uq_event_safety_requirements
  on event_safety_requirements(event_id, label, sort_order);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'event_safety_requirements_penalty_code_fkey'
  ) then
    alter table event_safety_requirements
      add constraint event_safety_requirements_penalty_code_fkey
      foreign key (event_id, penalty_code)
      references event_penalty_rules(event_id, code)
      on update cascade
      on delete set null;
  end if;
end$$;

create table if not exists rider_safety_checks (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references events(id) on delete cascade,
  moto_id uuid not null references motos(id) on delete cascade,
  rider_id uuid not null references riders(id) on delete cascade,
  requirement_id uuid not null references event_safety_requirements(id) on delete cascade,
  is_checked boolean not null default false,
  updated_at timestamptz not null default now(),
  updated_by text null
);

create unique index if not exists rider_safety_checks_unique
  on rider_safety_checks(event_id, moto_id, rider_id, requirement_id);
create index if not exists rider_safety_checks_moto_idx
  on rider_safety_checks(moto_id);

create table if not exists race_stage_config (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  category_id uuid not null references categories(id) on delete cascade,
  enabled boolean not null default false,
  max_riders_per_race int not null default 8,
  qualification_moto_count int not null default 2,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_race_stage_config_event_category
  on race_stage_config(event_id, category_id);

create table if not exists race_category_rule (
  id uuid primary key default uuid_generate_v4(),
  category_id uuid not null references categories(id) on delete cascade,
  min_riders int not null,
  enable_qualification boolean not null default false,
  enable_quarter_final boolean not null default false,
  enable_semi_final boolean not null default false,
  enabled_final_classes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_race_category_rule_category
  on race_category_rule(category_id);
create unique index if not exists uq_race_category_rule_category_min
  on race_category_rule(category_id, min_riders);

create table if not exists race_stage_result (
  id uuid primary key default uuid_generate_v4(),
  rider_id uuid not null references riders(id) on delete cascade,
  category_id uuid not null references categories(id) on delete cascade,
  stage race_stage not null,
  batch_id uuid,
  final_class final_class,
  position int,
  points int,
  created_at timestamptz not null default now()
);

create index if not exists idx_race_stage_result_category_stage
  on race_stage_result(category_id, stage);
create index if not exists idx_race_stage_result_rider
  on race_stage_result(rider_id);

create table if not exists user_event_roles (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id uuid not null references events(id) on delete cascade,
  role text not null,
  is_active boolean not null default true,
  assigned_by uuid references auth.users(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_user_event_roles_role check (
    upper(role) in (
      'SUPER_ADMIN',
      'ADMIN',
      'CHECKER',
      'FINISHER',
      'RACE_DIRECTOR',
      'RACE_CONTROL',
      'MC'
    )
  )
);

create unique index if not exists uq_user_event_roles_active
  on user_event_roles(user_id, event_id, upper(role));
create index if not exists idx_user_event_roles_event
  on user_event_roles(event_id, is_active);
create index if not exists idx_user_event_roles_user
  on user_event_roles(user_id, is_active);
create index if not exists idx_user_event_roles_role
  on user_event_roles(upper(role), is_active);

drop trigger if exists trg_user_event_roles_updated_at on user_event_roles;
create trigger trg_user_event_roles_updated_at
before update on user_event_roles
for each row execute function set_updated_at();

create table if not exists protests (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  moto_id uuid references motos(id) on delete set null,
  rider_id uuid references riders(id) on delete set null,
  reason text,
  note text,
  decision protest_decision not null default 'PENDING',
  created_by text,
  resolved_by text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists idx_protests_event
  on protests(event_id, created_at desc);
create index if not exists idx_protests_moto
  on protests(moto_id, created_at desc);
