-- Core schema for Pushbike Race Management System
create extension if not exists "uuid-ossp";

-- Enums
do $$
begin
  if not exists (select 1 from pg_type where typname = 'event_status') then
    create type event_status as enum ('UPCOMING','LIVE','FINISHED');
  end if;
  if not exists (select 1 from pg_type where typname = 'gender_type') then
    create type gender_type as enum ('BOY','GIRL','MIX');
  end if;
  if not exists (select 1 from pg_type where typname = 'moto_status') then
    create type moto_status as enum ('UPCOMING','LIVE','FINISHED');
  end if;
  if not exists (select 1 from pg_type where typname = 'result_status') then
    create type result_status as enum ('FINISH','DNF','DNS');
  end if;
end$$;

-- Shared helper to keep updated_at consistent
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- EVENTS
create table if not exists events (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  location text,
  event_date date not null,
  status event_status not null default 'UPCOMING',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_events_status on events(status);
create index if not exists idx_events_date on events(event_date);

drop trigger if exists trg_events_updated_at on events;
create trigger trg_events_updated_at
before update on events
for each row execute function set_updated_at();

-- CATEGORIES (auto-generated by year + gender)
create table if not exists categories (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  year int not null,
  year_min int not null default 2017,
  year_max int not null default 2017,
  capacity int,
  gender gender_type not null,
  label text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  constraint ck_categories_capacity check (capacity is null or capacity >= 0)
);

create index if not exists idx_categories_event on categories(event_id);
create index if not exists idx_categories_year_gender on categories(event_id, year, gender);
create unique index if not exists uq_categories_event_year_gender on categories(event_id, year, gender);

-- RIDERS
create table if not exists riders (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  name text not null,
  rider_nickname text,
  date_of_birth date not null,
  birth_year int generated always as (extract(year from date_of_birth)::int) stored,
  gender gender_type not null,
  plate_number int not null,
  plate_suffix char(1),
  no_plate_display text generated always as (
    plate_number::text || coalesce(plate_suffix::text, '')
  ) stored,
  club text,
  photo_url text,
  photo_thumbnail_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_rider_gender check (gender in ('BOY','GIRL')),
  constraint ck_plate_suffix check (plate_suffix is null or plate_suffix ~ '^[A-Z]$'),
  constraint ck_birth_year check (
    birth_year >= 2016
    and birth_year <= 2025
  )
);

create unique index if not exists uq_riders_plate_per_event on riders(event_id, plate_number, plate_suffix);
create index if not exists idx_riders_event on riders(event_id);
create index if not exists idx_riders_no_plate on riders(event_id, plate_number, plate_suffix);

drop trigger if exists trg_riders_updated_at on riders;
create trigger trg_riders_updated_at
before update on riders
for each row execute function set_updated_at();

-- MOTOS
create table if not exists motos (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  category_id uuid not null references categories(id) on delete cascade,
  moto_name text not null,
  moto_order int not null,
  status moto_status not null default 'UPCOMING',
  created_at timestamptz not null default now()
);

create index if not exists idx_motos_event on motos(event_id);
create index if not exists idx_motos_category on motos(category_id);

-- MOTO RIDERS
create table if not exists moto_riders (
  id uuid primary key default uuid_generate_v4(),
  moto_id uuid not null references motos(id) on delete cascade,
  rider_id uuid not null references riders(id) on delete cascade,
  created_at timestamptz not null default now()
);

create unique index if not exists uq_moto_rider on moto_riders(moto_id, rider_id);

-- RESULTS
create table if not exists results (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  moto_id uuid not null references motos(id) on delete cascade,
  rider_id uuid not null references riders(id) on delete cascade,
  finish_order int,
  result_status result_status not null default 'FINISH',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_results_moto_rider on results(moto_id, rider_id);
create index if not exists idx_results_moto on results(moto_id);
create index if not exists idx_results_event on results(event_id);
create unique index if not exists uq_results_moto_finish_order on results(moto_id, finish_order) where finish_order is not null;

drop trigger if exists trg_results_updated_at on results;
create trigger trg_results_updated_at
before update on results
for each row execute function set_updated_at();

-- RACE SCHEDULE
create table if not exists race_schedules (
  id uuid primary key default uuid_generate_v4(),
  event_id uuid not null references events(id) on delete cascade,
  moto_id uuid not null references motos(id) on delete cascade,
  schedule_time timestamptz,
  track_number int,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_race_schedules_event_moto on race_schedules(event_id, moto_id);
create index if not exists idx_race_schedules_event_time on race_schedules(event_id, schedule_time);

drop trigger if exists trg_race_schedules_updated_at on race_schedules;
create trigger trg_race_schedules_updated_at
before update on race_schedules
for each row execute function set_updated_at();

-- EVENT SETTINGS
create table if not exists event_settings (
  event_id uuid primary key references events(id) on delete cascade,
  event_logo_url text,
  sponsor_logo_urls text[] not null default '{}',
  base_price int not null default 250000,
  extra_price int not null default 150000,
  ffa_mix_min_year int,
  ffa_mix_max_year int,
  scoring_rules jsonb not null default '{}'::jsonb,
  display_theme jsonb not null default '{}'::jsonb,
  race_format_settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_event_settings_updated_at on event_settings;
create trigger trg_event_settings_updated_at
before update on event_settings
for each row execute function set_updated_at();
